CREATE DATABASE IF NOT EXISTS pf;
USE pf;
CREATE TABLE IF NOT EXISTS clint (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);